insert into car (model, maker, year) values ('Pajero', 'Mitsubishi', 1988,'car1.jpg');
insert into car (model, maker, year) values ('Express 1500', 'Chevrolet', 2005,'car2.jpg');
insert into car (model, maker, year) values ('Truck', 'Mitsubishi', 1996,'car3.jpg');
insert into car (model, maker, year) values ('Allante', 'Cadillac', 1993,'car4.jpg');
insert into car (model, maker, year) values ('Vision', 'Eagle', 1995,'car5.jpg');
insert into car (model, maker, year) values ('Countach', 'Lamborghini', 1987,'car6.jpg');
insert into car (model, maker, year) values ('Fiesta', 'Ford', 2012,'car7.jpg');
insert into car (model, maker, year) values ('CTS', 'Cadillac', 2003,'car8.jpg');
insert into car (model, maker, year) values ('Envoy', 'GMC', 1998,'car9.jpg');
insert into car (model, maker, year) values ('Sunbird', 'Pontiac', 1994,'car10.jpg');